model_path: "/home/data/panlingzhi/models"
output_path: "outputs"
sd_version: "v5"
model_id: "stable-diffusion-v1-5"
controlnet_id: "sd-controlnet-scribble"
controlnet_scale: 1

input_image: "data/truck-sample.png"
mask_image: "data/truck-mask.png"
cond_image: "data/motor.png"
prompt: "black motorbike"

seed: 65

step: 30
op_interval: 3
num_gradient_ops: 3
gamma: 0.6
lr_warmup: 0.01
lr: 0.05
lr_f: "exp"
coef: 40
momentum: 0.7

coef_f: "linear"

fp16: true

cfg: 7.5
W: 512
H: 512
num: 1


