model_path: "/home/data/panlingzhi/models"
output_path: "outputs"
sd_version: "v5"
model_id: "stable-diffusion-v1-5"
controlnet_id: "sd-controlnet-scribble"
controlnet_scale: 0.8
ipa_id: "ip_adapter"
ip_scale: 0.6

input_image: "data/truck-sample.png"
mask_image: "data/truck-mask.png"
ip_image: "data/starry.png"
cond_image: "data/motor.png"
prompt: "motorbike"

seed: 66

step: 30
op_interval: 3
num_gradient_ops: 3
gamma: 0.6

lr_warmup: 0.01
lr: 0.05
lr_f: "exp"
coef: 40
momentum: 0.7
cfg: 7.5
W: 512
H: 512
num: 1

coef_f: "linear"
fp16: true




