model_path: "/home/data/panlingzhi/models"
output_path: "outputs"
sd_version: "v5"
model_id: "stable-diffusion-v1-5"
ipa_id: "ip_adapter"
ip_scale: 0.6

input_image: "data/monet-sample.png"
mask_image: "data/monet-mask.png"
ip_image: "data/starry-sample.png"
prompt: "sky"

seed: 66

step: 50
op_interval: 5
num_gradient_ops: 10
gamma: 0.6
lr_warmup: 0.007
lr: 0.03
lr_f: "exp"
coef: 110
momentum: 0.7

coef_f: "linear"

fp16: true

cfg: 7.5
W: 512
H: 512
num: 1


