model_path: "/home/data/panlingzhi/models"
output_path: "outputs"
model_id: "stable-diffusion-v1-5"

input_image: "data/vase-sample.png"
mask_image: "data/vase-mask.png"
prompt: "vase"

cfg: 7.5
W: 512
H: 512
num: 1

seed: 66
step: 50
op_interval: 5
num_gradient_ops: 10
gamma: 0.6
lr_warmup: 0.007
lr: 0.03
lr_f: "exp"
coef: 110
coef_f: "linear"
momentum: 0.7
fp16: true



